name: server
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  snout_db:
    path: ../snout_db

  rfc_6901: ^0.1.1
  dotenv: ^4.1.0
  http: ^1.1.0
  
  eval_ex: ^1.1.8

dev_dependencies:
