name: snout_db
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.17.2
  decimal: ^2.3.3
  eval_ex: ^1.1.8
  json_annotation: ^4.8.1

  meta: ^1.11.0
  rfc_6901: ^0.1.1
  

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lint: 2.1.2