name: snout_db
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.17.1
  json_annotation: ^4.8.0

  rfc_6901: ^0.1.1
  
  eval_ex: ^1.1.7

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.5.4